# Generated by Django 5.2.10 on 2026-01-08 04:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('naturalidad', models.CharField(choices=[('TS', 'Técnico Superior'), ('FP', 'Formación Profesional')], max_length=2, verbose_name='Tipo')),
                ('duracion_meses', models.IntegerField(help_text='Duración total en meses', verbose_name='Duración (meses)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('curso_actual', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Curso Actual')),
                ('contacto_emergencia_nombre', models.CharField(max_length=200, verbose_name='Contacto de Emergencia')),
                ('contacto_emergencia_telefono', models.CharField(max_length=20, verbose_name='Teléfono de Emergencia')),
                ('contacto_emergencia_relacion', models.CharField(max_length=100, verbose_name='Relación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='sysapp.carrera', verbose_name='Carrera')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='sysapp.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('link_classroom', models.URLField(help_text='Link de Google Classroom', verbose_name='Link Classroom')),
                ('bimestre', models.IntegerField(blank=True, help_text='Solo para Técnico Superior', null=True, verbose_name='Bimestre')),
                ('orden', models.IntegerField(default=0, help_text='Orden de la materia en el plan', verbose_name='Orden')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='sysapp.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['carrera', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=50, unique=True, verbose_name='Nº de Recibo')),
                ('foto_recibo', models.ImageField(blank=True, null=True, upload_to='recibos/%Y/%m/', verbose_name='Foto del Recibo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('recibido_de', models.CharField(max_length=200, verbose_name='Recibido de')),
                ('suma_de', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='La suma de')),
                ('concepto', models.TextField(verbose_name='En concepto de')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('valido_hasta', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('numero_cuota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nº de Cuota')),
                ('importe_parcial', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Importe Parcial')),
                ('importe_total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Importe Total')),
                ('recibido_por', models.CharField(max_length=200, verbose_name='Recibido por')),
                ('estrellas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estrellas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sysapp.alumno', verbose_name='Alumno')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sysapp.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('cargo', models.CharField(choices=[('DOCENCIA', 'Docencia'), ('ADMINISTRATIVO', 'Administrativo'), ('DIRECCION', 'Dirección'), ('OTRO', 'Otro')], max_length=20, verbose_name='Cargo')),
                ('telefono_principal', models.CharField(max_length=20, verbose_name='Teléfono Principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Secundario')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='sysapp.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('presente', models.BooleanField(default=True, verbose_name='Presente')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='sysapp.funcionario', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Asistencia de Funcionario',
                'verbose_name_plural': 'Asistencias de Funcionarios',
                'ordering': ['-fecha'],
                'unique_together': {('funcionario', 'fecha')},
            },
        ),
    ]
