# Generated by Django 5.2.10 on 2026-01-12 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'cargo': 'DOCENCIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_asignadas', to='sysapp.funcionario', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='link_classroom',
            field=models.URLField(blank=True, help_text='Link de Google Classroom', verbose_name='Link Classroom'),
        ),
    ]
