# Generated by Django 5.2.10 on 2026-01-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0002_materia_docente_alter_materia_link_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='foto_comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
