# Generated by Django 5.2.10 on 2026-01-13 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0003_pago_foto_comprobante_pago_observaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='cantidad_cuotas',
            field=models.IntegerField(blank=True, default=1, help_text='Cantidad de cuotas pagadas', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_unitario',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Monto por cada cuota', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='nombre_cliente',
            field=models.CharField(blank=True, help_text='Nombre del cliente si no es alumno regular', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='validez_pago',
            field=models.DateField(blank=True, help_text='Fecha de validez del pago', null=True),
        ),
    ]
