# Generated by Django 5.2.10 on 2026-01-19 21:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0004_alter_pago_options_pago_cantidad_cuotas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='monto_matricula',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo de matrícula de la carrera', max_digits=10, verbose_name='Monto Matrícula (Gs.)'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='monto_mensualidad',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo mensual de la carrera', max_digits=10, verbose_name='Mensualidad (Gs.)'),
        ),
        migrations.AddField(
            model_name='materia',
            name='fecha_examen',
            field=models.DateField(blank=True, help_text='Fecha del examen de la materia', null=True, verbose_name='Fecha de Examen'),
        ),
        migrations.AddField(
            model_name='materia',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la materia', null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sysapp.alumno', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='importe_parcial',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Importe Parcial'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_cuota',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nº de Cuota'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='recibido_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Recibido de'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Recibido por'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='suma_de',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='La suma de'),
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(help_text='Número de factura o comprobante', max_length=50, verbose_name='Nº de Comprobante')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('categoria', models.CharField(choices=[('SERVICIOS', 'Servicios (Luz, Agua, Internet)'), ('SUELDOS', 'Sueldos y Salarios'), ('MATERIALES', 'Materiales y Suministros'), ('MANTENIMIENTO', 'Mantenimiento'), ('ALQUILER', 'Alquiler'), ('IMPUESTOS', 'Impuestos y Tasas'), ('OTROS', 'Otros Gastos')], max_length=20, verbose_name='Categoría')),
                ('concepto', models.TextField(help_text='Descripción detallada del gasto', verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto (Gs.)')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='egresos/%Y/%m/', verbose_name='Comprobante')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='sysapp.sede', verbose_name='Sede')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
