# Generated by Django 5.2.10 on 2026-01-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0006_pago_carrera_numero_recibo_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='importe_parcial',
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N? de Recibo'),
        ),
    ]
