# Generated by Django 5.2.10 on 2026-01-30 00:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0008_alter_pago_numero_cuota_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='numero_cuota',
            field=models.CharField(blank=True, help_text='Ej: 1 o 3,4,5', max_length=50, null=True, verbose_name='N? de Cuota'),
        ),
        migrations.CreateModel(
            name='CanjeEstrellas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Estrellas')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto/Premio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Canje')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='sysapp.alumno', verbose_name='Alumno')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canje de Estrellas',
                'verbose_name_plural': 'Canjes de Estrellas',
                'ordering': ['-fecha'],
            },
        ),
    ]
