# Generated by Django 5.2.10 on 2026-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0009_alter_pago_numero_cuota_canjeestrellas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='fecha_examen',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='materia',
            name='fecha_examen_final',
            field=models.DateField(blank=True, help_text='Fecha del examen final de la materia', null=True, verbose_name='Fecha Examen Final'),
        ),
        migrations.AddField(
            model_name='materia',
            name='fecha_examen_parcial',
            field=models.DateField(blank=True, help_text='Fecha del examen parcial de la materia', null=True, verbose_name='Fecha Examen Parcial'),
        ),
    ]
