# Generated by Django 5.2.10 on 2026-02-05 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0010_remove_materia_fecha_examen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('PAGO', 'Pago'), ('EGRESO', 'Egreso'), ('ALUMNO', 'Alumno'), ('CARRERA', 'Carrera'), ('MATERIA', 'Materia'), ('FUNCIONARIO', 'Funcionario'), ('SEDE', 'Sede')], max_length=20)),
                ('objeto_id', models.PositiveIntegerField()),
                ('motivo', models.TextField(verbose_name='Motivo de la eliminación')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('observaciones_decision', models.TextField(blank=True, null=True)),
                ('datos_objeto', models.JSONField(blank=True, help_text='Copia de los datos del objeto para mostrar en la notificación', null=True)),
                ('usuario_decide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_eliminacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_eliminacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Eliminación',
                'verbose_name_plural': 'Solicitudes de Eliminación',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
