# Generated by Django 5.2.11 on 2026-02-06 04:59

import sysapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0011_solicitudeliminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to=sysapp.models.path_comprobante_egreso, verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='foto_comprobante',
            field=models.ImageField(blank=True, null=True, upload_to=sysapp.models.path_comprobante_pago),
        ),
        migrations.AlterField(
            model_name='pago',
            name='foto_recibo',
            field=models.ImageField(blank=True, null=True, upload_to=sysapp.models.path_comprobante_pago, verbose_name='Foto del Recibo'),
        ),
    ]
