# Generated by Django
import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Alumno = apps.get_model('sysapp', 'Alumno')
    for row in Alumno.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
        
    Pago = apps.get_model('sysapp', 'Pago')
    for row in Pago.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
        
    Egreso = apps.get_model('sysapp', 'Egreso')
    for row in Egreso.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0012_alter_egreso_comprobante_alter_pago_foto_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='alumno',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, serialize=False),
        ),
    ]
