# Generated by Django 5.2.11 on 2026-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0014_alter_alumno_options_alter_alumno_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
