# Generated by Django 5.2.11 on 2026-02-16 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0015_alter_alumno_options_alter_alumno_curso_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='sysapp.carrera'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='sysapp.sede'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_cuota',
            field=models.CharField(blank=True, help_text='Ej: 1 o 3,4,5', max_length=50, null=True, verbose_name='Nº de Cuota'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº de Recibo'),
        ),
    ]
