# Generated by Django 5.2.11 on 2026-02-17 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0016_alter_alumno_carrera_alter_alumno_sede_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canjeestrellas',
            options={'ordering': ['-fecha'], 'verbose_name': 'Canje de Puntos', 'verbose_name_plural': 'Canjes de Puntos'},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='estrellas',
        ),
        migrations.AddField(
            model_name='pago',
            name='es_matricula',
            field=models.BooleanField(default=False, help_text='Si es matrícula, no se aplican puntos ni fechas de vencimiento', verbose_name='Es Matrícula'),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='puntos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='canjeestrellas',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Puntos'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='numero_comprobante',
            field=models.CharField(blank=True, help_text='Número de factura o comprobante (opcional)', max_length=50, null=True, verbose_name='Nº de Comprobante'),
        ),
    ]
