# Generated by Django 5.2.11 on 2026-02-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0017_alter_canjeestrellas_options_remove_pago_estrellas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=100, verbose_name='Entidad bancaria')),
                ('titular', models.CharField(max_length=150, verbose_name='Titular de la cuenta')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='sysapp.cuentabancaria', verbose_name='Cuenta bancaria destino'),
        ),
    ]
