# Generated by Django 5.2.11 on 2026-02-18 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0019_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciafuncionario',
            name='horas_trabajadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de horas trabajadas ese día (opcional)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas Trabajadas'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='funcionario',
            field=models.ForeignKey(blank=True, help_text='Seleccionar si el egreso corresponde al sueldo de un funcionario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_funcionario', to='sysapp.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='concepto',
            field=models.TextField(verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de Comprobante'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='fecha_examen_final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Examen Final'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='fecha_examen_parcial',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Examen Parcial'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cantidad_cuotas',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='es_matricula',
            field=models.BooleanField(default=False, verbose_name='Es Matrícula'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_unitario',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_cuota',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de Cuota'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='validez_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='sysapp.sede', verbose_name='Sede asignada'),
        ),
        migrations.AlterField(
            model_name='solicitudeliminacion',
            name='datos_objeto',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
